//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Movie()
        {
            this.Follows = new HashSet<Follow>();
            this.Categories = new HashSet<Category>();
        }

        public Movie(string name, bool isAnime, bool isTheater, string countryName, int yearRelease, string status, string content, string image, string trailer, string thumbnail, string season)
        {
            this.Name = name;
            this.isAnime = isAnime;
            this.isTheater = isTheater;
            this.CountryId = ModelMethod.getCountry(countryName);
            this.YearRelease = yearRelease;
            this.Status = status;
            this.Content = content;
            this.Image = image;
            this.Trailer = trailer;
            this.Thumbnail = thumbnail;
            this.Season = season;
            this.Follows = new HashSet<Follow>();
            this.Categories = new HashSet<Category>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public bool isAnime { get; set; }
        public bool isTheater { get; set; }
        public int CountryId { get; set; }
        public int YearRelease { get; set; }
        public string Status { get; set; }
        public string Content { get; set; }
        public string Image { get; set; }
        public string Trailer { get; set; }
        public string Thumbnail { get; set; }
        public string Season { get; set; }
    
        public virtual Country Country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Follow> Follows { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Category> Categories { get; set; }
    }
}
