//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Follows = new HashSet<Follow>();
            this.Rooms = new HashSet<Room>();
        }

        public User(string email, string password, string fullName, string createAt)
        {
            Email = email;
            Password = password;
            FullName = fullName;
            CreateAt = DateTime.ParseExact(createAt, "yyyy-MM-dd", System.Globalization.CultureInfo.InvariantCulture);
            isAdmin = false;
            this.Follows = new HashSet<Follow>();
            this.Rooms = new HashSet<Room>();
        }

        public string Email { get; set; }
        public string Password { get; set; }
        public string FullName { get; set; }
        public System.DateTime CreateAt { get; set; }
        public Nullable<bool> isAdmin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Follow> Follows { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Room> Rooms { get; set; }
    }
}
